name: Latest Release

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - 'v*'
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET Core 9
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Update appsettings.json version and debug
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        DEBUG=false
        echo "Updating appsettings.json file with version: $VERSION and debug set to: $DEBUG"
        jq --arg ver "$VERSION" --argjson dbg $DEBUG \
           '.AppInfo.Version = $ver | .AppInfo.Debug = $dbg' \
           FluxProDisplay/appsettings.json > tmp.json && mv tmp.json FluxProDisplay/appsettings.json

    - name: Build and publish
      run: dotnet publish -c Release -r win-x64 -p:SelfContained=false --property:PublishDir=$(pwd)/publish

    - name: Zip published output
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cd $(pwd)/publish
        zip -r ../antecfluxprodisplay.zip .
        cd ..

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v3
      with:
        files: antecfluxprodisplay.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
